#!/bin/bash

# Colors
BLACK='\033[1;30m'        # Black
RED='\033[1;31m'          # Red
GREEN='\033[1;32m'        # Green
YELLOW='\033[1;33m'       # Yellow
BLUE='\033[1;34m'         # Blue
CYAN='\033[1;36m'         # Cyan
WHITE='\033[1;37m'        # White
LIGHT_GREEN='\033[0;32m'  # Light Green


git () {
  if [ -n $1 ]; then
    git add . && git commit -m "$1" && git push
  else
    git add . && git commit -m "Automatic commit via mgr command" && git push
  fi

}

usage="$(basename "$0") [-h] [-g] -- script that automates stuff

where:
    -h  show this help text
    -g  add,commit, and push to Git in the current repo. Commit message can be passed like this: mgr -g 'commit message'"

while getopts ':hs:' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
    :) printf "missing argument for -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
    g) git ()
        exit
        ;;
   \?) printf "illegal option: -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
  esac
done

shift $((OPTIND - 1))

