name: Test Workflow
run-name: Tests
on: 
  push:
    branches:
      - dev
jobs:
  Dev-Branch-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project on Git
        uses: actions/checkout@v3.5.3

      - name: Adjust rights on installation script
        run: chmod 755 installation.sh

      - name: Execute installation script
        run: bash installation.sh

      - name: Test mgr command
        run: whoami

      - name: Test mgr command
        run: ls -la ~/.local/bin

      - name: Test mgr command
        run: ls -la $HOME/.local/bin
        

      - name: Test mgr command
        run: mgr

      - name: Test version function
        run: mgr -v