name: Test Workflow
run-name: Tests
on: 
  push:
    branches:
      - dev
jobs:
  Dev-Branch-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project on Git
        uses: actions/checkout@v3.5.3

      - name: test the installation script
        run: chmod 775 installation.sh && ./installation.sh

      - name: Test mgr command
        run: mgr

      - name: Test version function
        run: mgr -v