name: Test Workflow
run-name: Tests
on: 
  push:
    branches:
      - dev
jobs:
  Dev-Branch-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project on Git
        uses: actions/checkout@v3.5.3

      - name: Adjust rights on installation script
        run: chmod 755 installation.sh

      - name: Execute installation script
        run: bash installation.sh

      - name: Test mgr version
        run: pwd

      - name: Test mgr version
        run: bash mgr -v

      - name: Test mgr update
        run: bash mgr -u

      - name: install Python
        run: sudo apt install python3 && sudo apt install python3-venv

      - name: Test mgr python
        run: bash mgr -p

      - name: Create a Python venv
        run: mkdir python-test && cd python-test && bash $HOME/work/linux_manager/linux_manager/mgr -p venv && ls -la

      - name: Create a New Python Project
        run: cd ~ && bash $HOME/work/linux_manager/linux_manager/mgr -p python-repo-test cd python-repo-test && ls -la

      - name: Test mgr git
        run: bash mgr -g

      # - name: Check if current dev version is not already released
      #   run: check current tags on GH
