name: Test Workflow
run-name: Tests
on: 
  push:
    branches:
      - dev
jobs:
  Dev-Branch-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project on Git
        uses: actions/checkout@v3.5.3

      - name: Adjust rights on installation script
        run: chmod 755 installation.sh

      - name: Execute installation script
        run: bash installation.sh

      - name: Test mgr version
        run: bash mgr -v

      - name: Test mgr python
        run: bash mgr -p

      - name: Test mgr git
        run: bash mgr -g

      - name: Test mgr update
        run: bash mgr -u